### ISSUE TITLE
Responsiveness

### ISSUE THREAD

**Issue by kennybeyer** [Valerie-Wissenburg/web-iv-portfolio-site#1]
Navigation is silly and really silly at mobile. Logo gets too small at mobile. Images stack on top of each other at mobile on product page

**Comment by e-m-durham** [comment]
Also, icons in the footer too small. The images on the project page should break down more elegantly. Because the navigation is pretty critical, along with these other issues, the prototype would currently be assessed at "unsuccessful" so make sure you're making considerations for each screen size as you wrap things up.
